### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by antfu** [JeremyMeissner/slidev-theme-apple-basic#1]
Just found out this repo, the theme looks pretty nice!

I have added it to our [Theme Gallery](https://sli.dev/themes/gallery.html), just FYI.

Nice work, and thank you for making the theme for Slidev :)

**Comment by JeremyMeissner** [comment]
Thank you!

**Comment by antfu** [comment]
Do you have a Twitter handle, so I can shout this out on Twitter and @ you? 😁

**Comment by JeremyMeissner** [comment]
Oh yes, I'm @MeissnerJeremy I just DM you btw 😁
